CREATE TABLE XXCTS_RAJDEEP_PRJ_ITEM
(ITEM_ID NUMBER,
ITEM_NAME VARCHAR2(20));

DESC XXCTS_RAJDEEP_PRJ_ITEM;

INSERT INTO XXCTS_RAJDEEP_PRJ_ITEM VALUES(300, 'PEN-DRIVE');
INSERT INTO XXCTS_RAJDEEP_PRJ_ITEM VALUES(301, 'HARD-DISK');
INSERT INTO XXCTS_RAJDEEP_PRJ_ITEM VALUES(302, 'LAPTOP');
INSERT INTO XXCTS_RAJDEEP_PRJ_ITEM VALUES(303, 'TABLET');
INSERT INTO XXCTS_RAJDEEP_PRJ_ITEM VALUES(304, 'PHONE');

SELECT * FROM XXCTS_RAJDEEP_PRJ_ITEM;

--------------------------------------------------------------------------

CREATE OR REPLACE DIRECTORY RD_PRJ_RAJDEEP AS '/usr/tmp';-- CREATING A DIRECTORY
GRANT WRITE ON DIRECTORY RD_PRJ_RAJDEEP to public;-- GRANTING ACCESS TO THE DIRECTORY 

CREATE OR REPLACE PROCEDURE XXCTS_RD_PRJ_OUTBOUND_WRITE-- WRITE PROCEDURE
IS
  CURSOR ITEM_RAJ_CUR-- DECLARING THE CURSOR
  IS
    SELECT ITEM_ID, ITEM_NAME FROM XXCTS_RAJDEEP_PRJ_ITEM;
  V_FILE UTL_FILE.FILE_TYPE; -- File Handle
  V_DIR      VARCHAR2(25);
  v_filename VARCHAR2(25);
BEGIN
  V_DIR      := 'RD_PRJ_RAJDEEP';-- DIRECTORY 
  V_FILENAME := 'ITEM_RAJDEEP_DATA.csv';-- FILE WHERE THE DATAGET STORED
  V_FILE     := UTL_FILE.FOPEN(V_DIR,V_FILENAME,'w');-- W FOR WRITE
  UTL_FILE.PUT_LINE(V_FILE,'ITEM_ID ' || 'ITEM_NAME');
  FOR ITEM_RAJ_REC IN ITEM_RAJ_CUR
  LOOP
    UTL_FILE.PUT(V_FILE,ITEM_RAJ_REC.ITEM_ID);
    UTL_FILE.PUT_LINE(V_FILE, ' ' || ITEM_RAJ_REC.ITEM_NAME);
  END LOOP;
  UTL_FILE.FCLOSE(V_FILE);
END;

EXEC XXCTS_RD_PRJ_OUTBOUND_WRITE;
-------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE XXCTS_RD_PRJ_OUTBOUND_READ-- READ PROCEDURE
IS
  V_FILE UTL_FILE.FILE_TYPE; -- File Handle
  V_DIR      VARCHAR2(25);
  V_FILENAME VARCHAR2(25);
  V_OUT      VARCHAR2(50);
BEGIN
  V_DIR      := 'RD_PRJ_RAJDEEP';-- DIRECTORY
  V_FILENAME := 'ITEM_RAJDEEP_DATA.csv';-- DATA STORED 
  V_FILE     := UTL_FILE.FOPEN(V_DIR,V_FILENAME,'r');-- READ ACCESS
  LOOP
    BEGIN
      UTL_FILE.GET_LINE(V_FILE,V_OUT);
      DBMS_OUTPUT.PUT_LINE(V_OUT);
    EXCEPTION
    WHEN No_Data_Found THEN
      EXIT;
    END;
  END LOOP;
  UTL_FILE.FCLOSE(V_FILE);
END;


EXEC XXCTS_RD_PRJ_OUTBOUND_READ;
