LOAD DATA
INFILE'D:\Cognizant\Oracle EBS\EBS Project\MP_RAJDEEP_PRJ_INT2'
INSERT INTO TABLE MP_RAJDEEP_PRJ_INT2
Fields terminated by ","
Optionally enclosed by ' "" '
(
VENDOR_INTERFACE_ID,
VENDOR_SITE_CODE,
VENDOR_ID,
ZIP,
STATE,
VENDOR_SITE_INTERFACE_ID
)